### ISSUE TITLE
Breaks with Ember 1.11.0-beta.5

### ISSUE THREAD

**Issue by IanVS** [tzellman/ember-slide-show#7]
The initializer seems not to be working correctly in the latest Ember version, for upon startup I receive the error: 

```
Uncaught Error: Assertion Failed: Unable to find partial with name "slide-show/header"
```

Works fine with Ember `1.10.0`.

**Comment by IanVS** [comment]
Seems to be an Ember issue: https://github.com/emberjs/ember.js/issues/10744

But, the initializer style used here is deprecated and should be ypdated.

**Comment by tzellman** [comment]
Thanks. Should be resolved now.
